spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: update_server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  jpa:
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true